### ISSUE TITLE
Real-world example (my comment from Scott Hanselman blog)

### ISSUE THREAD

**Issue by Roman-Blinkov** [ignatandrei/Presentations#6]
Simple docker-compose example of stateful microservice (your own selfhosted private registry) published to internet using automated LetsEncrypt.
To create ./htpasswd file use
`docker run  --rm --entrypoint htpasswd registry:2 -Bbn mylogin mypassword  > ~/.htpasswd`
docker-compose.yaml

```
version: '2'
services:
  registry:
    image: registry:2
    restart: always 
    environment:
      VIRTUAL_HOST: registry.blinkov.com
      LETSENCRYPT_HOST: registry.blinkov.com
      LETSENCRYPT_EMAIL: admin@blinkov.com
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: 'Registry Realm'
      REGISTRY_AUTH_HTPASSWD_PATH: '/auth_htpasswd'
      REGISTRY_HTTP_ADDR: '0.0.0.0:5000'
      REGISTRY_STORAGE_MAINTENANCE: |-
        uploadpurging:
            enabled: false
        readonly:
            enabled: false
      REGISTRY_STORAGE_DELETE_ENABLED: 'false'
    volumes:
      - "/var/lib/registry"
      - ~/.htpasswd:/auth_htpasswd
      - "~/registry:/var/lib/registry"
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
      - "./my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"

```

This is example. This is not deeply-tested production-ready solution. Nginx need some tuning to be good reverse proxy for production usage.
I am using similar config as ingress in k8s with edited nginx buffers.
